services:
  backend:
    build: .
    env_file:
      - .env
    command: npm run build
    # Dev only
    # command: npm run start:dev
    volumes:
      - .:/usr/app/backend
      - /usr/app/backend/node_modules
    depends_on:
      - db
    links:
      - db
    ports:
      - ${BACKEND_PORT}:${BACKEND_PORT}

  db:
    image: mongo:latest
    container_name: db
    env_file:
      - .env
    ports:
      - "${DB_PORT}:27017"
    volumes:
      - dbdata-volume:/data/db
    environment:
      MONGO_INITDB_USERNAME: ${DB_USERNAME}
      MONGO_INITDB_PASSWORD: ${DB_PASSWORD}
      MONGO_INITDB_DATABASE: ${DB_DATABASE}

volumes:
  dbdata-volume:
